apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-client
  namespace: flink
spec:
  selector:
    matchLabels:
      app: minio-client
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minio-client
      namespace: flink  
    spec:
      containers:
      - name: minio-client
        image: minio/mc
        command: ["sleep"]
        args: ["infinity"]
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "150m"
        env:
        # MinIO access key and secret key
        - name: MINIO_ACCESS_KEY
          value: "minio"
        - name: MINIO_SECRET_KEY
          value: "minio123"
        - name: MININ_HOST
          value: "http://minio-service:9000"
        # mc alias set s3 $MINIO_HOST $MINIO_ACCESS_KEY $MINIO_SECRET_KEY